# -*- coding: utf-8 -*-

NORMAL = 0
LAUNCH_FAILED = 1
LOGIN_USER_FAILED = 2
CREATE_PROJECT_FAILED = 3
CREATE_PROJECT_CASE_FAILED = 4
HOME_TAB = 5
RESET_WND_DIALOG = 6
CLOSE_START_PAGE = 7
OUT_PUT_WND = 8
WELLPATH_EDITOR_VIEW = 9
HOLE_EDITOR_VIEW = 10

NOT_FOUND_TOP_WINDOW = 11

GENERAL_TAB = 12
TORQUE_DRAG_TAB = 13
HYDRAULICS_TAB = 14
CEMENTING_TAB = 15
SWABSURGE_TAB = 16
UB_HYDRAULICS_TAB = 17
WELLCONTROL_TAB = 18
BHA_DYNAMICS_TAB = 19
STUCK_PIPE_TAB = 20

NOT_BAR_TAB = 21

BAR_FOUND_FAIL = 22

NOT_FOUND_NEW_CASE_DATA = 0x7fffffff